package model

object GameConstants {
  val PLAYERS_HOLES_NUMBER = 6
  val STONES_INITIAL_AMOUNT = 6
  val NUMBER_OF_PLAYERS = 2

  val PLAYER_ONE_FIRST_HOLE_INDEX = 0
  val PLAYER_ONE_BASE_INDEX: Int = PLAYERS_HOLES_NUMBER

  val PLAYER_TWO_FIRST_HOLE_INDEX: Int = PLAYERS_HOLES_NUMBER + 1
  val PLAYER_TWO_BASE_INDEX: Int = PLAYERS_HOLES_NUMBER * NUMBER_OF_PLAYERS + 1

  val HOLES_BOARD_NUMBER: Int = PLAYERS_HOLES_NUMBER * NUMBER_OF_PLAYERS + 2
}
