import l3.{combine2, combine3, combine3Tail, find, findMultiple, findTail, into2, myLength, findMultipleTail}

object l3_test {

  def main(args: Array[String]): Unit = {
    println("Zadanie 1:")
    println(into2(List(-1, -3, -5, -7, -9, -11)))
    println(into2(List(2, 3, 4, 5, 6)))
    println(into2(List(-5.5, -2.1, -3.0, -1.0)))
    println(into2(List()))
    println("Zadanie 2:")
    println(myLength(List(2, 3, 4, 5, 6)))
    println(myLength(List("a", "b", "c", "d")))
    println(myLength(List()))
    println("Zadanie 3:")
    println(combine2(List(1, 2, 3), List(4, 5, 6)))
    println(combine2(List(1, 3, 5), List(2, 4)))
    println(combine2(List("a", "b", "c"), List()))
    println(combine2(List(), List(4.1, 5.2, 6.3)))
    println(combine2(List(), List()))
    println("Zadanie 4a:")
    println(find(List("ale", "ala", "ma", "kota"), "a"))
    println(find(List("ale", "ala", "ma", "kota"), "al"))
    println(find(List(), "a"))
    println(find(List(), ""))
    println("Zadanie 4b:")
    println(findTail(List("ale", "ala", "ma", "kota"), "a"))
    println(findTail(List("ale", "ala", "ma", "kota"), "al"))
    println(findTail(List(), "a"))
    println(findTail(List(), ""))
    println("Zadanie 4a (N wzorców):")
    println(findMultiple(List("ale", "ala", "ma", "kota"), List("al")))
    println(findMultiple(List("asd", "text example", "aaa", "texttext", "aab", "baa", "aba", "texaa", "textaaa"), List("text", "aa")))
    println(findMultiple(List("ala", "ma", "kota"), List()))
    println(findMultiple(List(), List("a", "b")))
    println(findMultiple(List(), List()))
    println("Zadanie 4b (N wzorców):")
    println(findMultipleTail(List("ale", "ala", "ma", "kota"), List("al")))
    println(findMultipleTail(List("asd", "text example", "aaa", "texttext", "aab", "baa", "aba", "texaa", "textaaa"), List("text", "aa")))
    println(findMultipleTail(List("ala", "ma", "kota"), List()))
    println(findMultipleTail(List(), List("a", "b")))
    println(findMultipleTail(List(), List()))
    println("Zadanie 5a:")
    println(combine3(List(1, 2, 3), List(4, 5, 6), List(7, 8, 9)))
    println(combine3(List(1), List(4, 5), List(7, 8, 9)))
    println(combine3(List(1, 2, 3), List(), List(7, 8, 9)))
    println(combine3(List(), List(), List()))
    println("Zadanie 5b:")
    println(combine3Tail(List(1, 2, 3), List(4, 5, 6), List(7, 8 ,9)))
    println(combine3Tail(List(1), List(4, 5), List(7, 8, 9)))
    println(combine3Tail(List(1, 2, 3), List(), List(7, 8, 9)))
    println(combine3Tail(List(), List(), List()))
  }

}
